spring:
  application:
    name: projetoagenda

  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
    username: postgres.gkxplzgbqcdzndgilgxo
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

api:
  security:
    token:
      secret: ${JWT_SECRET}

allowedOrigins: "*"
